---
#I had to edit .ssh/authorized_keys, to remove the following text:
#no-port-forwarding,no-agent-forwarding,no-X11-forwarding,command="echo 'Plea
- name: install Docker
  hosts: docker
  remote_user: ubuntu
  become: true
  tasks:
    - name: Install apt-transport-https
      become_user: root
      ansible.builtin.apt:
        name:
          - apt-transport-https
          - ca-certificates
          - lsb-release
          - gnupg
        state: latest
        update_cache: true

    - name: Add signing key
      become_user: root
      ansible.builtin.apt_key:
        url: "https://download.docker.com/linux/{{ ansible_distribution | lower }}/gpg"
        state: present

    - name: Add repository into sources list
      become_user: root
      ansible.builtin.apt_repository:
        repo: "deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/{{ ansible_distribution | lower }} {{ ansible_distribution_release }} stable"
        state: present
        filename: docker

    - name: Install Docker
      become_user: root
      ansible.builtin.apt:
        name:
          - docker
          - docker.io
          - docker-compose
          - docker-registry
        state: latest
        update_cache: true